apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-agent-service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "core-agent-service.name" . }}
    app.kubernetes.io/part-of: v9
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "core-agent-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: http
