{{- if and .Values.auth.enabled .Values.auth.tokenToXUser.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway-service.tokenToXUserPluginConfigMapName" . }}
  labels:
    {{- include "api-gateway-service.authLabels" . | nindent 4 }}
data:
  .traefik.yml: |-
{{ .Files.Get "plugins/token-to-x-user/.traefik.yml" | nindent 4 }}
  go.mod: |-
{{ .Files.Get "plugins/token-to-x-user/go.mod" | nindent 4 }}
  token_to_x_user.go: |-
{{ .Files.Get "plugins/token-to-x-user/token_to_x_user.go" | nindent 4 }}
{{- end }}
