{{- if .Values.envFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-agent-service.fullname" . }}-env-file
  labels:
    app.kubernetes.io/name: {{ include "core-agent-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .env: |
{{ .Values.envFile.content | indent 4 }}
{{- end }}
