{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-agent-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "core-agent-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "core-agent-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: app
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
{{- end -}}
