apiVersion: v2
name: anybackup-agent
description: Umbrella chart for the AnyBackup Agent release package
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: v9-infra
    version: 0.1.0
    repository: "file://charts/v9-infra"
  - name: v9-services
    version: 0.1.0
    repository: "file://charts/v9-services"
  - name: core-agent-service
    version: 0.1.0
    repository: "file://charts/core-agent-service"
  - name: agent-web
    version: 0.1.0
    repository: "file://charts/agent-web"
    condition: agent-web.enabled
  - name: api-gateway-service
    version: 0.1.0
    repository: "file://charts/api-gateway-service"
    condition: api-gateway-service.enabled
  - name: auth-service
    version: 0.1.6
    repository: "file://charts/auth-service"
    condition: auth-service.enabled
  - name: conversation-service
    version: 0.1.0
    repository: "file://charts/conversation-service"
    condition: conversation-service.enabled
