from enum import StrEnum


class ErrorReason(StrEnum):
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    SENSITIVE_INPUT_REJECTED = "SENSITIVE_INPUT_REJECTED"
    CONVERSATION_ARCHIVED = "CONVERSATION_ARCHIVED"
    CONVERSATION_EXPIRED = "CONVERSATION_EXPIRED"
    CONVERSATION_BUSY = "CONVERSATION_BUSY"
    CONVERSATION_STATE_CONFLICT = "CONVERSATION_STATE_CONFLICT"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    CONVERSATION_ACCESS_DENIED = "CONVERSATION_ACCESS_DENIED"
    CONVERSATION_WRITEBACK_STALE = "CONVERSATION_WRITEBACK_STALE"
    CHILD_CONVERSATION_MISMATCH = "CHILD_CONVERSATION_MISMATCH"


class DomainError(Exception):
    def __init__(self, reason: ErrorReason, message: str | None = None) -> None:
        self.reason = reason
        super().__init__(message or reason.value)
