apiVersion: v2
name: api-gateway-service
description: Global API gateway based on Traefik with forward-auth middleware.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: traefik
    version: 39.0.8
    repository: https://traefik.github.io/charts
