namespace: v9
imageRegistry: ""
imageTag: alpha1
imagePullPolicy: IfNotPresent

commonEnv:
  - name: APP_ENV
    value: alpha

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

services:
  - name: conversation-service
    enabled: true
    replicas: 1
    containerPort: 8080
    servicePort: 80
    repo: git@github.com:example/conversation-service.git
    ref: main
    env: []
