apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: management
      port: {{ .Values.keycloak.service.ports.management }}
      targetPort: management
      protocol: TCP
